=OFFSET($B$2,ROW()-2,ROW()-2,1,1)

=INDIRECT("RC[-1]",FALSE)/SUM($B2:INDIRECT("RC[-2]",FALSE))


=INDIRECT("RC[-2]",FALSE)/SUM(INDIRECT(SUBSTITUTE(ADDRESS(COLUMN(),ROW(),4),COLUMN(),)&"2"):INDIRECT(SUBSTITUTE(ADDRESS(COLUMN(),ROW(),4),COLUMN(),)&COLUMN()-3))

=HARMEAN(INDIRECT("RC[-2]",FALSE),INDIRECT("RC[-1]",FALSE))

=SUM(OFFSET($B$2,0,COLUMN()-6):OFFSET($B$2,COLUMN()-7,COLUMN()-6))/SUM($B$2:OFFSET($B$2,COLUMN()-7,COLUMN()-7))
